version: '3.1'

services:
    api-mongo:
      image: mongo
      ports:
       - 27017:27017
      environment:
        MONGODB_USERNAME: root
        MONGODB_PASSWORD: example
        MONGODB_DATABASE: api-mongo